# Generated by Django 5.0.2 on 2024-03-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='extra_jun',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='salary',
            name='extra_dec',
            field=models.BooleanField(default=False),
        ),
    ]
