# Generated by Django 5.0.2 on 2024-03-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_salary_extra_jun_alter_salary_extra_dec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='employe',
            old_name='place_id',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_id',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='location_id',
            new_name='location',
        ),
    ]
