# Generated by Django 5.0.2 on 2024-03-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_rename_job_id_employe_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='desciption',
            new_name='description',
        ),
    ]
